from .company_view import CompanyViewSet
from .role_view import RoleViewSet
from .department_view import DepartmentViewSet
from .user_view import UserViewSet
from .macroprocess_view import MacroProcessViewSet
from .process_view import ProcessViewSet
from .subprocess_view import SubProcessViewSet
from .indicator_view import IndicatorViewSet
from .result_view import ResultViewSet
