# Generated by Django 4.2.5 on 2025-05-14 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('calculationMethod', models.CharField(choices=[('percentage', 'Porcentaje'), ('rate_per_1000', 'Tasa por 1000'), ('rate_per_10000', 'Tasa por 10000'), ('average', 'Promedio'), ('ratio', 'Razón')], max_length=50)),
                ('measurementUnit', models.CharField(max_length=255)),
                ('numerator', models.TextField()),
                ('numeratorResponsible', models.CharField(max_length=255)),
                ('numeratorSource', models.CharField(max_length=255)),
                ('numeratorDescription', models.TextField()),
                ('denominator', models.TextField()),
                ('denominatorResponsible', models.CharField(max_length=255)),
                ('denominatorSource', models.CharField(max_length=255)),
                ('denominatorDescription', models.TextField()),
                ('target', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('measurementFrequency', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual')], max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('updateDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MacroProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('updateDate', models.DateField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('updateDate', models.DateField(auto_now=True)),
                ('macroProcess', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.macroprocess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('updateDate', models.DateField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.process')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerator', models.FloatField()),
                ('denominator', models.FloatField()),
                ('calculatedValue', models.FloatField(blank=True, null=True)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('updateDate', models.DateField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('quarter', models.PositiveIntegerField(blank=True, null=True)),
                ('semester', models.PositiveIntegerField(blank=True, null=True)),
                ('headquarters', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.headquarters')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.indicator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='indicator',
            name='subProcess',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.subprocess'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
